/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_moon_ndk_URL */

#ifndef _Included_com_moon_ndk_URL
#define _Included_com_moon_ndk_URL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_moon_ndk_URL
 * Method:    getHttpServer01
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_moon_ndk_URL_getHttpServer01
  (JNIEnv *, jclass);

/*
 * Class:     com_moon_ndk_URL
 * Method:    getHttpServer02
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_moon_ndk_URL_getHttpServer02
  (JNIEnv *, jclass);

/*
 * Class:     com_moon_ndk_URL
 * Method:    getHttpServer03
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_moon_ndk_URL_getHttpServer03
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
